all:
	g++ add_template.cpp -o test_add
	g++ swap_template.cpp -o test_swap
	g++ vector_template.cpp -o test_vector

add:
	g++ add_template.cpp -o test_add
swap:
	g++ swap_template.cpp -o test_swap
vector:
	g++ vector_template.cpp -o test_vector

clean:
	rm test_*
